language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=latest WP_MULTISITE=1
- WP_VERSION=4.1 WP_MULTISITE=0
- WP_VERSION=4.1 WP_MULTISITE=1
matrix:
  allow_failures:
  - php: hhvm
  fast_finish: true
before_script:
- bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: cd tests; phpunit;
notifications:
  slack:
    rooms:
      secure: VnU5ZZoiWmdhlqvG0Q4Nsu54ON7YbbN9pKUgWFdwf70mjd6ojzyBSGwLeD0dSlj1b1y1rmXZSNoe4ZwyG9TB73Q0qBVnwpedOSRxM+jV1XnpvR+QQ37VhvMWz24U+mONIvUNp9UdKZBP4mwu0lr3r2G8+rJXI01d347OCK7wiXQ=
    on_success: change
    on_failure: always
    on_start: always