sudo: false
dist: trusty
language: php
cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=1
matrix:
  include:
  - php: 5.3
    dist: precise
  - php: 5.4
  - php: 5.5
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: nightly
  allow_failures:
  - php: nightly
  exclude:
  - php: 5.3
    env: WP_VERSION=4.1 WP_MULTISITE=1
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=1
  - php: 5.4
    env: WP_VERSION=4.1 WP_MULTISITE=1
  - php: 5.4
    env: WP_VERSION=latest WP_MULTISITE=1
  - php: 5.5
    env: WP_VERSION=4.1 WP_MULTISITE=1
  - php: 5.5
    env: WP_VERSION=latest WP_MULTISITE=1
  - php: 7.1
    env: WP_VERSION=4.1 WP_MULTISITE=0
  - php: 7.1
    env: WP_VERSION=4.1 WP_MULTISITE=1
  - php: 7.0
    env: WP_VERSION=4.1 WP_MULTISITE=0
  - php: 7.0
    env: WP_VERSION=4.1 WP_MULTISITE=1
  fast_finish: true
before_install:
   - |
      if [[ "$SKIP_XDEBUG_REMOVE" != "true" ]]; then
        phpenv config-rm xdebug.ini
        echo "xdebug removed";
      fi
before_script:
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - mysql --version
  - phpunit --version
  - phpenv versions
script: cd tests; phpunit;
notifications:
  slack:
    rooms:
      secure: e2xmbwOoagh/rZIqUnx15HcTv5hZGxykvg8Tj0ENGi/bLcXgrEYxs2hpW+nzGggmSl22Eh+6wLRo62L0dEIIo1n+yknqDdAbVG7lmnX7Tc45JNgxWtSmAPzC3wAp0e9w1hy8HILPjYLxl0G7eXUvo3mKVRCCyD/Cyz5dDicE8tQ=
    on_success: change
    on_failure: always
    on_start: always
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
      - "%{commit_message}"
